### ISSUE TITLE
Missing utility aomf2bin

### ISSUE THREAD

**Issue by mxlgv** [ogdenpm/c-ports#3]
Hello, I really miss the utility for aomf2bin, it helps me convert files for RK-86. Is it possible to add it to this repository and include it in the Linux build? Here is my patch with which I collected it:
```diff
diff --git a/aomf2bin/main.c b/aomf2bin/main.c
index 216870e..17ebee4 100644
--- a/aomf2bin/main.c
+++ b/aomf2bin/main.c
@@ -27,6 +27,11 @@
 #include <ctype.h>
 #include <stdint.h>
 
+#if !defined(WIN32) && !defined (_WIN32)
+#include <strings.h>
+#define _stricmp strcasecmp
+#endif
+
 void showVersion(FILE *fp, bool full);
 
 enum {
@@ -75,7 +80,7 @@ inline uint16_t word(uint8_t *buf) {
 #endif
 }
 
-inline uint32_t dword(uint8_t *buf) {
+static inline uint32_t dword(uint8_t *buf) {
 #ifdef SAFECONVERT
     return buf[0] + (buf[1] >> 8) + (buf[2] >> 16) + (buf[3] >> 24);
 #else

```

**Comment by ogdenpm** [comment]
Sorry I missed this. I have just posted an update to the tool-src repository which is the master for aomf2bin. There is now support for Linux build of all the tools except disIntelLib, which is written in C# and currently uses the older Windows .Net framework
